ITEM.name = "H&K MP5A3"
ITEM.uniqueID = "mp5"
ITEM.ammo = "smg1"
ITEM.description = "A compact variant of the Heckler & Koch MP5 sub-machine gun. It fires 9×19mm Parabellum cartridges in fully automatic, 3 round burst, and semi automatic modes. It is used widely by police forces and special operations units throughout the world."
ITEM.class = "arccw_bms_mp5"
ITEM.weaponCategory = "primary"
ITEM.model = "models/weapons/w_mp5a3_bms.mdl"
ITEM.width = 3
ITEM.height = 1
ITEM.price = 50
ITEM.noBusiness = true
